name: Run dbt cloud
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # dbt action使うために、環境変数に与えたシークレットアクセスキーの情報からファイルを復元させる
      - name: Translate secrets of base64 into json
        env:
          JSON_DECODE: ${{ secrets.GCP_CREDENTIAL_JSON_DECODED_BASE64 }}
        run: | # .github/workflows/profiles内で参照している。
          echo $JSON_DECODE | base64 --decode > <YourSecretKey>

      # dbt depsしないと各種dbtコマンドが使えないので実施
      - name: Install dbt deps
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt deps"

      # =================================
      # mergeされたら全モデルをdeployしなおす(TOBE : いつか変更モデルだけbuildに変えたい)

      - name: Build dbt models for the prod environment.
        uses: mwhitaker/dbt-action@master
        with: # profiles.ymlが含まれるdirectoryを--profiles-dirで指定する。
          dbt_command: "dbt build --profiles-dir .github/"

      # =================================
      # dbt docsの作成・デプロイを行う

      - name: Generate dbt docs
        uses: mwhitaker/dbt-action@master
        with: # profiles.ymlが含まれるdirectoryを--profiles-dirで指定する。
          dbt_command: "dbt docs generate --profiles-dir .github/"

      - name: Deploy dbt docs to S3
        uses: docker://amazon/aws-cli:2.0.7
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3 cp --recursive --region ap-northeast-1 target <YourS3BucketPath>
